/**
 * Re-export hooks from SDK hooks for backward compatibility
 * 
 * This file maintains compatibility with existing components while
 * transitioning to the new SDK-based architecture.
 */

export * from './sdk-hooks';

// Legacy exports for backward compatibility
export {
  useLogin,
  useRegister,
  useLogout,
  useCurrentUser,
  useConversations,
  useConversation,
  useMessages,
  useCreateConversation,
  useSendMessage,
  useDeleteConversation,
  useConversationMessages,
  useUpdateConversation,
  useDocuments,
  useDocument,
  useUploadDocument,
  useDeleteDocument,
  useReprocessDocument,
  useDocumentStatus,
  useDocumentSearch,
  useConversationSearch,
  useHealth,
  useSystemStatus,
  useSystemMetrics,
  useSystemHealth,
  useSystemStats,
  useAnalyticsOverview,
  useUsageAnalytics,
  useUserStats,
  usePerformanceMetrics,
  useMcpServers,
  useMcpTools,
  useMcpStats,
  useAddMcpServer,
  useDeleteMcpServer,
  useUpdateMcpServer,
  useLlmProfiles,
  useCreateProfile,
  useDeleteProfile,
  useCreateLlmProfile,
  useUpdateLlmProfile,
  useDeleteLlmProfile,
  useSetDefaultLlmProfile,
  usePrompts,
  useCreatePrompt,
  useDeletePrompt,
  useCreatePromptTemplate,
  useUpdatePromptTemplate,
  useDeletePromptTemplate,
  useSetDefaultPromptTemplate,
  usePromptCategories,
  usePromptTemplates,
  useUpdateUserProfile,
  useUpdateProfile,
  useChangePassword,
  useSearchDocuments,
  useSearchSuggestions,
  useToolStats,
  useToggleTool,
  useEnhancedBasicHealth,
  useEnhancedDetailedHealth,
  useEnhancedCurrentUser,
} from './sdk-hooks';