"""Shared schemas package for API and SDK.

Contains Pydantic schema definitions that are used by both the API server
and the client SDK to ensure consistency and eliminate duplication.
"""

# Import all schemas to make them available from this package
from .admin import *
from .analytics import *
from .auth import *
from .base import *
from .common import *
from .conversation import *
from .database import *
from .document import *
from .health import *
from .llm_profile import *
from .mcp import *
from .prompt import *
from .search import *
from .task import *
from .tool_calling import *
from .user import *

__all__ = [
    # Admin schemas
    "AdvancedSearchResponse",
    "ConversationStatsResponse",
    "DocumentStatsResponse",
    "ProfileStatsResponse",
    "PromptCategoriesResponse",
    "PromptStatsResponse",
    "QueueResponse",
    "RegistryStatsResponse",
    "SearchResponse",
    "TaskMonitorResponse",
    "TaskStatsResponse",
    "TaskStatusResponse",
    "WorkersResponse",
    # Analytics schemas
    "AnalyticsExportPayload",
    "AnalyticsExportResponse",
    "AnalyticsOverviewPayload",
    "AnalyticsOverviewResponse",
    "AnalyticsPerformancePayload",
    "AnalyticsPerformanceResponse",
    "AnalyticsTrendsPayload",
    "AnalyticsTrendsResponse",
    "AnalyticsUsagePayload",
    "AnalyticsUsageResponse",
    "AnalyticsUserAnalyticsPayload",
    "AnalyticsUserAnalyticsResponse",
    "ConversationsOverview",
    "DBPerformanceEntry",
    "DailyStat",
    "DailyTrend",
    "DetailedUserAnalyticsPayload",
    "DocumentProcessingPerformance",
    "DocumentsOverview",
    "SystemHealthScore",
    "SystemMetricsInfo",
    "TopUser",
    "TrendSummary",
    "UsageMetrics",
    "UsersOverview",
    # Auth schemas
    "LoginRequest",
    "PasswordResetConfirm",
    "PasswordResetRequest",
    "RegisterRequest",
    "Token",
    # Base schemas
    "BaseModelSchema",
    "BaseSchema",
    "IdMixin",
    "IdSchema",
    "TimestampMixin",
    "TimestampSchema",
    # Common schemas
    "APIResponse",
    "BaseResponse",
    "BulkOperationResponse",
    "ConfigurationResponse",
    "DetailedHealthCheckResponse",
    "ErrorDetail",
    "ErrorDetails",
    "ErrorResponse",
    "FileUploadResponse",
    "HealthCheckResponse",
    "MetricsResponse",
    "PaginatedResponse",
    "PaginationParams",
    "SearchParams",
    "TokenResponse",
    "ValidationErrorResponse",
    # Conversation schemas
    "ArchiveConversationsResult",
    "ArchivePreviewItem",
    "ArchivePreviewResponse",
    "ChatRequest",
    "ChatResponse",
    "ConversationBase",
    "ConversationCreate",
    "ConversationExportData",
    "ConversationExportDataCSV",
    "ConversationExportDataJSON",
    "ConversationExportDataResponse",
    "ConversationExportDataText",
    "ConversationExportInfoResponse",
    "ConversationExportResponse",
    "ConversationListResponse",
    "ConversationMetadata",
    "ConversationResponse",
    "ConversationSearchCriteria",
    "ConversationSearchData",
    "ConversationSearchMatchingMessage",
    "ConversationSearchResult",
    "ConversationSearchUserInfo",
    "ConversationStats",
    "ConversationStatsConversations",
    "ConversationStatsData",
    "ConversationStatsMessages",
    "ConversationStatsRecentActivity",
    "ConversationStatsUserEngagement",
    "ConversationUpdate",
    "ExportInfo",
    "ExportedMessage",
    "ImportConversationResult",
    "MessageBase",
    "MessageCreate",
    "MessageListResponse",
    "MessageResponse",
    "StreamCompleteResponse",
    "StreamContentResponse",
    "StreamEndResponse",
    "StreamErrorResponse",
    "StreamStartResponse",
    "StreamToolCallResponse",
    # Document schemas
    "AdvancedSearchData",
    "BackgroundTaskResponse",
    "BulkReprocessResponse",
    "CleanupDeletedResponse",
    "CleanupDryRunResponse",
    "CleanupPreviewItem",
    "DocumentChunkResponse",
    "DocumentFileTypeStats",
    "DocumentListResponse",
    "DocumentProcessingStats",
    "DocumentRecentActivity",
    "DocumentResponse",
    "DocumentSearchCriteria",
    "DocumentSearchRequest",
    "DocumentSearchResponse",
    "DocumentSearchResult",
    "DocumentStatisticsData",
    "DocumentStorageStats",
    "DocumentTopUser",
    "DocumentUpdate",
    "DocumentUploadResponse",
    "DocumentUserInfo",
    "ProcessingConfigRequest",
    "ProcessingConfigResponse",
    "ProcessingStatusResponse",
    "QueueStatusResponse",
    # Health schemas
    "ApplicationHealthData",
    "CacheHealthData",
    "CacheStats",
    "DatabaseHealthData",
    "DatabaseHealthResponse",
    "DatabaseTableInfo",
    "DetailedHealthCheckData",
    "DetailedHealthCheckPayload",
    "FastMCPHealthData",
    "LivenessPayload",
    "LivenessProbeData",
    "LivenessResponse",
    "OpenAIHealthData",
    "PerformanceMetricsData",
    "PerformanceMetricsPayload",
    "PerformanceMetricsResponse",
    "ReadinessComponentsPayload",
    "ReadinessProbeData",
    "ReadinessResponse",
    "ServiceStatus",
    "ServicesHealthData",
    "ServicesHealthPayload",
    "ServicesHealthResponse",
    "SystemMetricsData",
    "SystemMetricsPayload",
    "SystemMetricsResponse",
    "SystemResourceMetrics",
    # LLM Profile schemas
    "LLMProfileCreate",
    "LLMProfileResponse",
    "LLMProfileStatisticsData",
    "LLMProfileUpdate",
    # MCP schemas
    "MCPBatchUsageSchema",
    "MCPConnectionStatusSchema",
    "MCPConnectionTestSchema",
    "MCPDiscoveryRequestSchema",
    "MCPDiscoveryResultSchema",
    "MCPHealthStatusSchema",
    "MCPListFiltersSchema",
    "MCPOpenAIToolsResponseSchema",
    "MCPServerCreateSchema",
    "MCPServerListResponse",
    "MCPServerSchema",
    "MCPServerUpdateSchema",
    "MCPStatsResponse",
    "MCPToolCreateSchema",
    "MCPToolExecutionRequestSchema",
    "MCPToolExecutionResultSchema",
    "MCPToolListResponse",
    "MCPToolResponse",
    "MCPToolUpdateSchema",
    "MCPToolUsageStatsSchema",
    "MCPToolsResponse",
    "OpenAIToolCallSchema",
    "OpenAIToolSchema",
    # Prompt schemas
    "PromptCategoriesData",
    "PromptCreate",
    "PromptListResponse",
    "PromptResponse",
    "PromptStatisticsData",
    "PromptUpdate",
    # Search schemas
    "SearchSuggestion",
    "SearchSuggestionData",
    # Task schemas
    "ActiveTaskInfo",
    "ActiveTasksData",
    "ActiveTasksResponse",
    "DefaultProfileResponse",
    "DocumentProcessingStats",
    "ProfileParametersData",
    "ProfileParametersResponse",
    "ProfileStatisticsData",
    "ProfileStatisticsResponse",
    "ProfileValidationData",
    "ProfileValidationResponse",
    "QueueInfo",
    "QueueStatusData",
    "QueueStatusResponse",
    "TaskInfo",
    "TaskMonitoringData",
    "TaskMonitoringResponse",
    "TaskStatisticsData",
    "TaskStatisticsResponse",
    "TaskSystemStatusData",
    "TaskSystemStatusResponse",
    "TasksSummary",
    "WorkerInfo",
    "WorkerStatusData",
    "WorkerStatusResponse",
    "WorkersSummary",
    # Tool calling schemas
    "ToolCallResult",
    "ToolCallSummary",
    "ToolHandlingMode",
    # User schemas
    "UserBase",
    "UserCreate",
    "UserDetailResponse",
    "UserListResponse",
    "UserPasswordUpdate",
    "UserResponse",
    "UserSearchParams",
    "UserStatsResponse",
    "UserUpdate",
]
